#!/usr/bin/env bash
# Configure access to an EXISTING PostgreSQL amoCRM database.
# Does NOT install, create, migrate, or start PostgreSQL.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="$ROOT_DIR/.env"

echo "=== amoCRM read-only SQL — install ==="
echo "This script only configures access to an existing PostgreSQL database."
echo "It will NOT create/start PostgreSQL, tables, users, or migrations."
echo

if ! command -v node >/dev/null 2>&1; then
  echo "ERROR: Node.js is required (Node 22+ recommended for OpenClaw)." >&2
  exit 1
fi

NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if [[ "$NODE_MAJOR" -lt 20 ]]; then
  echo "ERROR: Node.js >= 20 required (found $(node -v))." >&2
  exit 1
fi

echo "Installing npm dependencies..."
npm install

# Plugin imports openclaw/plugin-sdk at runtime. Prefer the host OpenClaw install.
if command -v openclaw >/dev/null 2>&1; then
  OPENCLAW_ROOT="$(node -p "try{require('path').dirname(require.resolve('openclaw/package.json'))}catch(e){''}" 2>/dev/null || true)"
  if [[ -z "$OPENCLAW_ROOT" && -d /usr/lib/node_modules/openclaw ]]; then
    OPENCLAW_ROOT="/usr/lib/node_modules/openclaw"
  fi
  if [[ -n "$OPENCLAW_ROOT" && -d "$OPENCLAW_ROOT" ]]; then
    echo "Linking host OpenClaw SDK from $OPENCLAW_ROOT ..."
    npm install --no-save --no-package-lock "$OPENCLAW_ROOT" >/dev/null 2>&1 \
      || npm install --no-save "$OPENCLAW_ROOT" || true
  fi
fi

prompt() {
  local var_name="$1"
  local label="$2"
  local default="${3:-}"
  local secret="${4:-0}"
  local value=""

  if [[ "$secret" == "1" ]]; then
    if [[ -n "$default" ]]; then
      read -r -s -p "$label [$default]: " value
    else
      read -r -s -p "$label: " value
    fi
    echo
  else
    if [[ -n "$default" ]]; then
      read -r -p "$label [$default]: " value
    else
      read -r -p "$label: " value
    fi
  fi

  if [[ -z "$value" ]]; then
    value="$default"
  fi

  printf -v "$var_name" '%s' "$value"
}

prompt AMOCRM_DB_HOST "PostgreSQL host" "127.0.0.1"
prompt AMOCRM_DB_PORT "PostgreSQL port" "5432"
prompt AMOCRM_DB_NAME "Database name" "amocrm"
prompt AMOCRM_DB_USER "Database user" ""
prompt AMOCRM_DB_PASSWORD "Database password" "" 1
prompt AMOCRM_DB_SSLMODE "SSL mode (disable|allow|prefer|require|verify-ca|verify-full)" "prefer"

if [[ -z "$AMOCRM_DB_USER" ]]; then
  echo "ERROR: database user is required." >&2
  exit 1
fi

if [[ -z "$AMOCRM_DB_PASSWORD" ]]; then
  echo "ERROR: database password is required." >&2
  exit 1
fi

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh — do not commit
AMOCRM_DB_HOST=${AMOCRM_DB_HOST}
AMOCRM_DB_PORT=${AMOCRM_DB_PORT}
AMOCRM_DB_NAME=${AMOCRM_DB_NAME}
AMOCRM_DB_USER=${AMOCRM_DB_USER}
AMOCRM_DB_PASSWORD=${AMOCRM_DB_PASSWORD}
AMOCRM_DB_SSLMODE=${AMOCRM_DB_SSLMODE}
EOF
chmod 600 "$ENV_FILE"

echo
echo "Saved configuration to .env (password not printed)."
echo "Checking connection..."

if ! npm run check-connection; then
  echo
  echo "ERROR: connection check failed."
  echo "Fix host/port/name/user/password/sslmode and re-run scripts/install.sh"
  exit 1
fi

echo
echo "Building TypeScript..."
npm run build

if command -v openclaw >/dev/null 2>&1; then
  echo "Generating OpenClaw plugin metadata..."
  if openclaw plugins build --entry ./dist/index.js; then
    echo "Plugin metadata OK."
  else
    echo "WARNING: openclaw plugins build failed. You can retry later:"
    echo "  npm run plugin:build"
  fi
else
  echo "NOTE: openclaw CLI not found in PATH."
  echo "After copying this package onto the OpenClaw host, run:"
  echo "  npm run plugin:build"
fi

echo
echo "=== Install finished ==="
echo
echo "Next steps (on the OpenClaw server):"
echo "  1. Ensure this directory is on the server (already done if you ran install there)."
echo "  2. Register the plugin:"
echo "       openclaw plugins install --link \"$ROOT_DIR\""
echo "       # or: openclaw plugins install \"$ROOT_DIR\""
echo "  3. Enable it:"
echo "       openclaw plugins enable amocrm-readonly-sql"
echo "  4. Optional: put DB settings into openclaw.json under"
echo "       plugins.entries.amocrm-readonly-sql.config"
echo "     (otherwise AMOCRM_DB_* from .env / environment are used)."
echo "  5. Restart gateway:"
echo "       openclaw gateway restart"
echo "  6. Verify:"
echo "       openclaw plugins inspect amocrm-readonly-sql --runtime"
echo "  7. In the bot, ask e.g. «Сколько сейчас активных сделок?»"
echo
echo "This project does not create, start, or maintain PostgreSQL."
echo "It only connects to an existing database with the credentials you provided."
